tailwind.config.ts

- `tailwind.config` 파일의 gap에만 저장해두면, `gap-2xl`에서만 사용할 수 있고, `padding`이나 `margin` 등 다양한 간격에서는 사용할 수 없음
- 디자인 시스템 상의 `Gap`은 `CSS` 상의 `gap`만 의미하는 것이 아니라, 일반적인 "간격"을 의미함
- 따라서, `spacing`에 저장해두어 `gap`, `padding`, `margin`에서 모두 해당 디자인 시스템을 사용할 수 있도록 함
[사용 예시]
- `figma` 상 item spacing : gap/4sx => tailwind 상 `gap-4xs`
- `figma` 상 padding : gap/4xs => tailwind 상 `p-4xs`

[🔨chore]: figma 상의 gap 속성을 tailwind 상 spacing으로 변경

---

.storybook/main.ts

`Next Image` 는 `svg`를 사용할 수가 없어서 `svgr` 라이브러리를 통해 `svg` 이미지를 불러오도록 했다. 
하지만 `storybook` 에서는 해당 `svg`를 읽을 수 없다는 오류가 발생
Next local에서는 아이콘이 잘 보임
storybook에서의 오류
`.storybook/main.ts` 파일에 config를 추가해줬다.
- https://velog.io/@ckstn0777/nextjs13-storybook-svgr
- https://github.com/storybookjs/storybook/issues/18557#issuecomment-1426150038

[🔨chore]: storybook에서 svgr 사용 가능하도록 설정

---

src/components/IndexPanel/IndexPanel.style.ts
src/components/IndexPanel/IndexPanel.tsx
src/components/index.ts
src/stories/IndexPanel.stories.tsx

> 목차 패널은 어디서 사용되든지 `Item`을 동일하게 가져갈 것으로 예상되어, 그대로 구현했습니다. (`IndexPanel/Item`을 통한 커스터마이징 불가)
사용할 때 배너, 설명, 간단 용례, 참고자료 및 문헌, 댓글에 대한 `ref`를 설정해서 `props`로 전달해줘야 한다.
- 좌측 storybook, 우측 local
- 좌측에서는 `Item`의 `width`가 더 길어 보인다. 하지만, `local`에서는 정상적으로 보이는 모습을 확인할 수 있다.
- 해결 해야하는가?? 🤔 급하거나 중요한건 아닌 것 같아서 해결하지 않았다.
- `IndexPanelItemLabelText` 컴포넌트보다 `interaction` 컴포넌트가 상위에 덮여있기 때문에, `IndexPanelItemLabelText` 를 감싸는 `span` 태그에는 `hover`가 정상 동작하지 않는다. (오른쪽은 정상 동작시 모습임)
- `IndexPanelItem`와 `IndexPanelItemLabelText`로 나뉘어져있던걸 하나로 합쳤습니다! (어차피 layout 설정은 없고 color 설정만 있었기에 가능했음)
- 이제 잘 작동합니다~
~~- `Interaction` 컴포넌트를 어떻게 수정해야 좋을지 혹시 아이디어가 있으시다면 환영입니다 ㅠㅠ~~

[✨feat]: IndexPanel 컴포넌트 구현

---

src/components/Button/Button.style.tsx
src/components/Button/Button.theme.ts
src/components/Button/Button.tsx
src/components/Button/Button.types.ts
src/components/index.ts
src/stories/Button.stories.tsx

> figma [button 디자인 시스템](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%92%A0%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=228-59754&p=f&m=dev)을 기반으로 button component 구현을 진행했습니다. 스토리북에서 확인 가능합니다. :>
> 인터랙션 컴포넌트가 `ComponentContainer` 하단에 위치하다 보니 `tabIndex`를 사용해 확인했을 때 `ComponentContainer` (e.g. button component라면 `button`의 최상위 부모 DOM)가 먼저 잡히고, 하위의 `InteractionComponent` 포커스가 잡힙니다.
그래서 포커스가 같은 컴포넌트에 두 번 번갈아서 나타난다는 문제 상황이 발생하고 있어요.
→ `ComponentContainer`에 적용된 기본 focus 스타일, `InteractionComponent`에 적용된 focus 스타일
해결 방법은 찾는 중입니다! 🥹

[✨feat]: button component 구현

---

src/components/Badge/Badge.types.ts
src/components/ContextMenu/Combobox.style.ts
src/components/ContextMenu/Combobox.tsx
src/components/ContextMenu/ContextMenu.style.ts
src/components/ContextMenu/ContextMenu.theme.ts
src/components/ContextMenu/ContextMenu.tsx
src/components/ContextMenu/ContextMenu.types.ts
src/components/ContextMenu/ContextMenuItem.style.ts
src/components/ContextMenu/ContextMenuItem.tsx
src/components/Interaction/Interaction.style.ts
src/components/Interaction/Interaction.types.ts
src/components/index.ts
src/stories/ContextMenu/Combobox.stories.tsx
src/stories/ContextMenu/ContextMenu.stories.tsx
src/stories/ContextMenu/ContextMenuItem.stories.tsx

> storybook에서 확인할 수 있습니다.
- ContextMenu 컴포넌트입니다.
> 추가로 ContextMenu.Item과 Combobox 컴포넌트를 개별적으로 확인하실 수 있습니다.
`ContextMenu.Item`의 `width`가 `storybook`과 `local`에서 다르게 나타납니다 ㅠㅠ
- storybook
- local
- 일단은 local에서 정상적으로 보이기 때문에 별다른 조치를 취하지 않았습니다. (원인 파악 불가 ㅠㅠ)
- 추후 Fade 컴포넌트가 만들어지면 추가해줘야할 것 같습니다.
- 현재는 overflow시 scroll되도록 `overflow: auto` 설정을 해뒀고, 스크롤 형태는 숨겨둔 상태입니다!

[✨feat]: ContextMenu 컴포넌트 구현

---

src/components/Button/Button.style.tsx
src/components/Button/Button.tsx
src/components/Interaction/Interaction.style.ts
src/styles/designSystem.tsx

- `button` 태그에 `Interaction` 컴포넌트를 입힐 시에, `focus`가 `button`태그에 한번, `Interaction` 컴포넌트에 한번, 총 두번 입혀지는 문제 발견 
- 이는 사용자 경험을 매우 저해하는 일이므로 해결이 필요
- `Interaction` 컴포넌트에 있던 `focus` 스타일을 `DESIGN_SYSTEM` 객체에 저장하고, `Interaction` 컴포넌트는 `hover`, `active`만 조절하도록 함.

[🐛fix]: focus 인터랙션 분리 (Button 태그에 focus 두번 잡히는 오류 수정)

---

src/app/_components/Home.style.ts
src/app/_components/HomeBanner.style.ts
src/app/_components/HomeBanner.tsx
src/app/page.tsx
src/components/ContextMenu/Combobox.tsx
src/components/ContextMenu/ContextMenu.tsx
src/stories/Badge/Badge.ComponentType.stories.tsx
src/stories/Badge/Badge.Label.stories.tsx
src/stories/Badge/Badge.stories.tsx
src/stories/Callout/Callout.Interactive.stories.tsx
src/stories/Callout/Callout.stories.tsx

- 로그인 페이지 작업하기 전, 랜딩페이지가 필요해서 임시로 제작했습니다. 
추후 `Banner` 컴포넌트가 제작되고 랜딩페이지 디자인이 확정되면 싹 수정해도 괜찮습니다!
- 각 페이지마다 `_components`라는 폴더를 만들어서, 그 페이지에서만 사용되는 컴포넌트를 제작하면 어떨까요? 
현재 제작된 컴포넌트를 한번 더 조합해서 페이지에 간단하게만 사용하고 싶을 때 유용할 것 같아서 생각해봤습니다! 의견 부탁드립니다 ☺️
(요거 여쭤보려구 해당 브랜치에 임시 랜딩페이지 제작을 했습니다.. 양해 부탁드립니다 😅)

[📝docs]: Fade 컴포넌트 deprecated / 임시 랜딩페이지 제작

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/Avatar.types.ts
src/components/Button/Button.tsx
src/components/Callout/Callout.Interactive.tsx
src/components/Chip/Chip.tsx
src/components/IndexPanel/IndexPanel.tsx
src/components/NavigationBar/NavItem.tsx
src/components/SocialAuth/SocialAuthButton.tsx
src/stories/Avatar.stories.tsx

- Avatar 컴포넌트에서 Badge를 보이고 안 보이게 설정할 수 있어야 하는데 관련 prop이 부재했음
> storybook에서는 해당 prop을 Boolean형태로 껐다 켰다 할 수 있도록 했습니다

[🐛fix]: Avatar 컴포넌트에 누락된 prop 추가

---

src/app/login/signin/_components/SignIn.style.ts
src/app/login/signin/_components/SignInButton/SignInButton.style.ts
src/app/login/signin/_components/SignInButton/SignInButton.tsx
src/app/login/signin/_components/SignInFooter/SignInFooter.style.ts
src/app/login/signin/_components/SignInFooter/SignInFooter.tsx
src/app/login/signin/_components/SignInJob/SignInJob.style.ts
src/app/login/signin/_components/SignInJob/SignInJob.tsx
src/app/login/signin/_components/SignInProfile/SignInProfile.style.ts
src/app/login/signin/_components/SignInProfile/SignInProfile.tsx
src/app/login/signin/_components/SignInProfile/SignInProfileImage.style.ts
src/app/login/signin/_components/SignInProfile/SignInProfileImage.tsx
src/app/login/signin/_components/SignInProfile/SignInProfileNickname.style.ts
src/app/login/signin/_components/SignInProfile/SignInProfileNickname.tsx
src/app/login/signin/_components/SignInTitle/SignInTitle.style.ts
src/app/login/signin/_components/SignInTitle/SignInTitle.tsx
src/app/login/signin/page.tsx
src/constants/chips.ts
src/constants/messages.ts

> `/login/signin` 페이지에서 확인하실 수 있습니다.
--- | --- |
1. `countLimit`을 지정할 수가 없습니다. `40`으로 고정되어 있습니다.
2. `labelText`를 자유롭게 할 수가 없습니다. (예시 사진의 경우, 필수를 뜻하는 `*`부분은 주황색이어야 함)
3. `border` 두께가 다릅니다..! (예시 사진의 경우 `stroke.normal`이어야 하는데 `stroke.bold`가 입력되는 것 같아요)
4. `InputField`의 prop 중 오타가 있습니다! `isNagative` → `isNegative`
5. `width`가 fix되어 있습니다ㅠㅠ 예시 사진의 경우에는 `100%`로 설정해줘야 합니다.. 
- 1번과 2번의 `countLimit`와 `labelText` 관련 문제를 해결하기 위해서 `label`부분과 `caption`부분을 분리하는 것 어떻게 생각하시나요? 그 부분은 컴포넌트 사용할 때 자유롭게 조합하고 제작해서 사용할 수 있도록 하는 거죠!
```ts
export const InputField({
// ...
label,
caption
}: IInputField & {
label : React.ReactNode;
caption : React.ReactNode;
}) {
// ...
```
- 5번의 경우 제가 [Dialog 컴포넌트 PR](https://github.com/JECT-Study/Componote-FE/pull/41)에서 문제상황 2에서 언급한 것과 마찬가지로 `style` prop을 뚫어서 개별적으로 style을 조절할 수 …

[✨feat]: 회원가입 페이지 UI 완성

---

package-lock.json
package.json
src/api/interceptor.ts
src/api/login.ts
src/app/@modal/(.)login/page.tsx
src/app/@modal/default.tsx
src/app/layout.tsx
src/app/login/page.tsx
src/app/page.tsx
src/components/Dialog/Dialog.Login.tsx
src/components/Dialog/Dialog.tsx
src/components/NavigationBar/NavigationBar.tsx
src/components/SocialAuth/SocialAuthButton.tsx
src/constants/api.ts
src/hooks/api/useAuthUrlQuery.ts
src/hooks/api/useLoginMutation.ts
src/hooks/api/useSocialLoginQuery.ts
src/hooks/useReactQuery.tsx
src/types/login.ts

- 랜딩 페이지에서 로그인 버튼을 누르면 Modal이 뜹니다
- 여기서 버튼을 누르면 각 소셜 로그인 Authorize 페이지로 이동
- 이후 랜딩페이지로 redirect 되면서 `code`가 함께 옴
- URL의 `param`으로 온 `code`를 추출하여 (`useSearchParams()` 활용) 소셜로그인 요청
- 소셜로그인 GET 요청을 통해 받은 `isRegister`에 따라서 `login` 로직을 실행시키거나 `signin`페이지로 이동시킴
추후 상태관리 라이브러리 도입을 통해 해결 예정
- 근데 어떻게 해야되는지 모르겠어서 못함.. `"use client"`없애고 싶은데 커스텀 훅으로 빼도 `"use client"`는 있어야해서... 고민...🤔

[✨feat]: Login 기본 기능 구현

---

src/app/component/page.tsx
src/components/ContextMenu/ContextMenu.style.ts
src/components/ContextMenu/ContextMenu.theme.ts
src/components/ContextMenu/ContextMenu.tsx
src/components/ContextMenu/ContextMenu.types.ts
src/components/ContextMenu/ContextMenuItem.style.ts
src/components/ContextMenu/ContextMenuItem.tsx
src/components/Toolbar/Toolbar.style.ts
src/components/Toolbar/Toolbar.tsx
src/constants/contextMenuLabels.ts

- Toolbar 컴포넌트에 `useState`를 통해 `ContextMenu`가 열렸는지, 닫혔는지를 관리 => 열린 경우에만 ContextMenu가 보여지도록 함
- Toolbar가 사용되는 페이지에서 `ContextMenuItem`에 들어갈 `string` 배열을 전달해줘야 함 (예시로는 [`src/app/component/page.tsx`](https://github.com/JECT-Study/Componote-FE/pull/55/files#diff-64bf80da23535807f010b27f2b317f06c50c6c691a0c04fd530d4e0336888b5f) 파일 확인)
- `ContextMenuItem`의 `width`가 이상함
- ContextMenu에 width 프롭을 추가함
- figma에 적혀있는 `158px` 대신 `160px`로 설정함 (아래 사진은 158px로 설정했을 경우)
- DevMode 사용 불가로 px값으로 설정함

[♻️refactor]: Toolbar에 ContextMenu 적용하기

---

.eslintrc.js
src/app/designsystem/page.tsx
src/components/Chip/Chip.group.style.ts
src/components/Layout/Layout.style.ts
src/components/Pages/DesignSystem/DesignCardContainer.style.ts
src/components/Pages/DesignSystem/DesignCardContainer.tsx
src/components/index.ts

> figma [design system page UI 플로우](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%92%A0%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=7052-180723&m=dev)을 기반으로 design system page UI 구현을 진행했습니다. 아래와 같습니다.
> `DesignSystemCard` component의 prop으로 버튼의 이미지를 넘겨주어야 하는데, 이를 위해 아이콘을 불러와야 합니다. 이 과정이 SSR에서 지원되지 않아 page에서 `use client`를 선언해 줘야 하는 문제가 발생하고 있습니다. 🥲 
> 추후 디자인 시스템 페이지 작업 시 button list 컴포넌트 하나를 더 생성해 거기서 이미지를 관리할 수 있도록 해 줘야 할 것 같습니다. 아직 로직은 고민 중이라 작업 진행하게 되면 반영하도록 하겠습니다!

[✨feat]: design system page UI 구현

---

src/components/Pages/Signup/SignupButton/SignupButton.tsx
src/components/Pages/Signup/SignupProfile/SignupProfileNickname.tsx
src/utils/validateNickname.ts

- 회원가입 페이지에서 닉네임 입력에 대한 유효성 검사 로직을 추가했습니다.
- 닉네임에 특수문자나 공백이 포함된 경우, 10자 이내가 아닌 경우, 영문/숫자/한글이 아닌 경우 
=> 버튼 Disable 및 InputField Negative 표시함

[✨feat]: 회원가입시 닉네임 유효성 검사 로직 추가

---

src/api/componentDetail.ts
src/app/component/[componentId]/page.tsx
src/components/Banner/Banner.document.tsx
src/components/Banner/Banner.types.ts
src/components/Card/Card.component.style.tsx
src/constants/messages.ts
src/hooks/api/component/useComponentListInfiniteQuery.ts
src/hooks/api/componentDetail/useComponentDetailQuery.tsx
src/stories/Banner/Banner.document.stories.tsx
src/types/componentDetail.ts

> component detail page 세부 내용 표시 구현이 완료되었습니다. [기능 명세서](https://www.notion.so/1204-97fc832ca93b42c8a0479f353723fd6d) 비고에 적혀 있는 것처럼 댓글 및 북마크는 구현되지 않은 상태이니 참고 부탁드립니다. 댓글 및 북마크 버튼 인터랙션은 작동하며, 클릭 시 이벤트는 발생하지 않습니다. (동영 님과 논의 후 결정한 사항입니다! :>)
> 디자인 시스템 페이지가 아직 미구현된 상태라 `보러 가기` 버튼을 클릭해도 라우팅이 이루어지지 않습니다. 디자인 시스템 페이지 구현 완료되는 대로 추가 구현 예정입니다.
[NEXT.JS useParams 공식 문서](https://nextjs.org/docs/app/api-reference/functions/use-params)

[✨feat]: component detail page 세부 내용 표시

---

src/api/component.ts
src/app/component/page.tsx
src/constants/api.ts
src/hooks/api/component/useComponentListInfiniteQuery.ts

> component list API가 변경되어 요청 시 end point 및 함수명을 수정해 주었습니다. 
```ts
componentList: (
page: number = 0,
size: number = 10,
types: string = "",
sort: string = "asc",
) => `/components?&types=${types}&page=${page}&size=${size}&sort=${sort}`,
```
```ts
export const getComponentList = async (
page: number,
size: number,
types: string,
sort: string,
) => {
const { data } = await axiosInstance.get(
`${END_POINT.componentList(page, size, types, sort)}`,
);
return data;
};
```

[👽fix]: component list API 변경에 따른 수정

---

src/app/designsystem/page.tsx
src/components/Card/Card.designSystem.style.ts
src/components/Card/Card.designSystem.tsx
src/components/Card/Card.types.ts
src/components/Pages/DesignSystem/DesignSystemCards.tsx
src/stories/Card/Card.designSystem.stories.tsx
src/types/api/component.ts
src/types/api/designSystem.ts
src/types/common/pageData.ts

> 당장 파악한 미구현 사항 및 수정 사항만 반영해 두었습니다. 잠재적인 문제 및 미구현 사항이 더 있을 수 있으니 나중에 검토 부탁드려요. :> 
_**top section 클릭 시**_
_**platform button 클릭 시**_
_**1. device label이 title text와 겹쳐 보이는 문제**_
_**2. device label의 위치가 카드 레이아웃 내에서 이상하게 표시되는 문제**_
_**1. device label이 title text와 겹쳐 보이는 문제**_
> `DeviceLabelBox`에 있던 `position: absoulte` 속성을 제거해 주었습니다.
```css
position: absolute;
right: 0rem;
top: 0.125rem;
```
_**2. device label의 위치가 카드 레이아웃 내에서 이상하게 표시되는 문제**_
> `TopSection`에 `width: 100%` 속성을 추가해 주었습니다.
```
width: 100%
```

[✨feat]: design system page 목록 미구현 항목 추가 구현

---

src/app/designsystem/page.tsx
src/components/Pages/DesignSystem/DesignSystemCards.tsx
src/constants/contextMenuLabels.ts
src/constants/designSystemFilterLabel.ts
src/hooks/api/designSystem/useDesignSystemInfiniteQuery.ts
src/types/enum/componentFilter.ts
src/types/enum/designSystemFilters.ts

> design system page 정렬 기능 구현이 완료되었습니다. 자세한 기능 명세는 [기능 명세서 6-2-4](https://www.notion.so/1204-97fc832ca93b42c8a0479f353723fd6d)에서 확인하실 수 있습니다. :> API에는 정렬 조건이 `이름순/추천순`만 구현되어 있어 두 가지 조건만 `context menu labels`에 추가해 두었습니다.

[✨feat]: design system page 정렬 구현

---

src/api/designSystem.ts
src/app/designsystem/page.tsx
src/components/Chip/Chip.group.tsx
src/components/Toolbar/Toolbar.tsx
src/constants/api.ts
src/hooks/api/designSystem/useDesignSystemInfiniteQuery.ts
src/store/designSystem/useDesignSystemFilterStore.ts
src/types/enum/designSystemFilters.ts

- 디자인 시스템 필터링 기능을 구현했습니다.
문제는 아니고 논의 할 내용입니다.
지금 reset버튼을 누르면 컴포넌트 필터와 디자인 시스템 필터가 모두 초기화되도록 했습니다.
Toolbar 안에서 컴포넌트페이지와 디자인 시스템 페이지를 구분할 수 있는 방법이 없어서 이렇게 했는데 논의해보고 리팩토링하면 좋을 것 같습니다~!

[✨feat]: 디자인 시스템 페이지 필터 기능 구현

---

src/app/announce/page.tsx
src/app/component/[componentId]/page.tsx
src/app/component/page.tsx
src/app/designsystem/page.tsx
src/app/mybookmark/page.tsx
src/app/page.tsx
src/app/profile/page.tsx
src/components/NavigationBar/NavigationBar.tsx
src/components/NavigationBar/NavigationBar.types.ts

- 상단바의 로그인 버튼 / Avatar 표시 여부를 위해 전달하는 `isAuthrized` prop을 제거함
어차피 전역으로 상태관리 되기 때문에 해당 prop이 불필요해짐

[♻️refactor]: 상단바 isAuthorized prop 제거

---

src/hooks/api/profileEdit/useProfileEditMutation.ts

- 프로필 편집 후 프로필 페이지로 돌아왔을 때 회원 정보가 업데이트 되지 않는 오류 수정
- refectch 사용하여 해결했습니다.

[🐛fix]: 프로필 편집 후 프로필 페이지에 userInfo 바로 업데이트
