- tailwind.config.ts
- 디자인 시스템 중 scheme에 있는 `stroke`/`opacity`/`gap`/`radius `전부 설정
- `figma` : `stroke/none`
- `tailwindCSS` : `stroke-none`
- `figma` : `opacity/08`
- `tailwindCSS` : `opacity-8`
- `figma` : `gap/2xl`
- `tailwindCSS` : `gap-2xl`
- `figma` : `radius/circle`
- `tailwindCSS` : `rounded-circle`
> [🔨chore]: scheme 디자인토큰 적용

- next.config.ts
- package-lock.json
- package.json
- Next에서 svg를 편리하게 사용하기 위해 설치함
사용 예시
```tsx
import Image from "next/image"
import Icon from "public/icons/Icon.svg"
// ...
<Image src={Icon} ... />
```
> [🔨chore]: svgr 설치

- src/components/Divider/Divider.style.ts
- src/components/Divider/Divider.tsx
- src/components/index.ts
- src/stories/Divider.stories.tsx
> 스토리북에서 컴포넌트에 대한 정보를 조금 더 상세하게 확인할 수 있도록 옵션을 추가했습니다! 해당 주석은 옵션에 대한 이해를 돕기 위함이고, 너무 많은 주석은 코드 가독성을 해친다고 생각해 PR에만 작성해 두었습니다. 
```tsx
const meta = {
title: "Components/Divider", // 스토리북 내에서의 카테고리 및 컴포넌트 이름
component: Divider, // 해당 스토리가 사용할 컴포넌트
parameters: {
layout: "centered", // 스토리북에서 컴포넌트를 중앙에 배치
},
tags: ["autodocs"], // 자동 문서화 태그
argTypes: {
stroke: {
control: { type: "select" }, // 스토리북의 UI에서 선택할 수 있는 드롭다운으로 설정
options: ["normal", "bold", "bolder", "boldest"], // 선택 가능한 옵션
defaultValue: "normal", // 기본값 설정
},
layout: {
control: { type: "select" }, // 스토리북의 UI에서 선택할 수 있는 드롭다운으로 설정
options: ["horizontal", "vertical"], // 선택 가능한 옵션
defaultValue: "horizontal", // 기본값 설정
},
},
} satisfies Meta<typeof Divider>;
```
> 아래처럼 상세하게 컴포넌트 모양 및 사용법 확인이 가능합니다. 
> 색상은 우선 `hex` 값을 넣어 둔 상태고, 추후 컬러 토큰 …
> [✨feat]: Divider component 구현

- src/styles/theme.ts
- shadow 사용 방법
```css
box-shadow : ${({ theme }) => theme.shadow.overlay}
```
- interaction 사용 방법
```ts
${({ theme }) => theme.interaction.normal}
```
- `bold`, `normal`, `subtle`의 `:hover`, `:active`(pressed), `:focus-visible`(focused)가 담겨 있음 `disabled`는 내부적으로 필요한 css 속성이 따로 없기 때문에 구현하지 않았음
> [✨feat]: shadow와 interaction 디자인 시스템 theme에 추가

- src/components/Interaction/Interaction.style.ts
- src/styles/designSystem.tsx
사용 방법
- 필요한 컴포넌트의 하위 컴포넌트로 `InteractionContainer`를 넣는다.
예시
```tsx
import InteractionContainer from "../Interaction/Interaction.style";
return (
<S.CalloutContainer $size={$size}> 
<S.CalloutTitleContainer> 
<S.CalloutTitleText $size={$size}>{titleText}</S.CalloutTitleText> 
</S.CalloutTitleContainer> 
<InteractionContainer $variant="accent" $density="normal" /> 
</S.CalloutContainer> );
```
⭐  중요!! 이때 상위 컴포넌트(이 경우 `S.CalloutContainer`)의 `position`은 `relative`여야 한다.
- 이 컴포넌트는 `styled-component`고 따로 React 컴포넌트로 만들지 않아도 될 것 같아서 `index.ts`에 안 넣었습니다. 
어차피 `src/components` 디렉토리 내에서만 쓰일 것 같습니다!
- [원티드](https://www.wanted.co.kr/)의 버튼에 `Interaction` 컴포넌트를 참고했습니다.
> [✨feat]: Interaction 컴포넌트 구현

- src/components/Callout/Callout.Interactive.style.ts
- src/components/Callout/Callout.Interactive.tsx
- src/components/Callout/Callout.style.ts
- src/components/Callout/Callout.tsx
- src/components/index.ts
- src/stories/Callout/Callout.Interactive.stories.tsx
- `Callout/Basic` 컴포넌트와 레이아웃이나 색상, 아이콘 등이 다른 부분이 있어서 새로운 컴포넌트로 구현했습니다.
> storybook에서 확인할 수 있습니다.
- `Interactive` 컴포넌트 머지 된 후로 주석 풀고 해당 컴포넌트 적용
> [✨feat]: Callout/Interactive 컴포넌트 구현

- .eslintrc.js
- src/app/component/page.tsx
- src/components/Chip/Chip.group.style.ts
- src/components/Chip/Chip.group.tsx
- src/components/Chip/Chip.style.tsx
- src/components/Chip/Chip.theme.ts
- src/components/Chip/Chip.tsx
- src/components/Chip/Chip.types.ts
- src/components/Chip/chipGroup.ts
- src/components/Footer/Footer.tsx
- src/components/Logo/Logo.style.ts
- src/components/Logo/Logo.tsx
- src/components/index.ts
- src/constants/messages.ts
- src/stories/Chip/Chip.group.stories.tsx
- src/stories/Chip/Chip.stories.tsx
- src/stories/Logo.stories.tsx
> figma [chip 디자인 시스템](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%92%A0%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=7206-135268&m=dev)을 기반으로 chip component 구현을 진행했습니다. 스토리북에서 확인 가능합니다. :>
_**chip component**_
_**chip group component**_
> [PR#22](https://github.com/JECT-Study/Componote-FE/pull/22#issuecomment-2559586736)에서 지예 님과 논의한 내용을 기반으로 logo component 리팩토링을 완료했습니다. :> 스타일 관련 분기는 모두 `DOM`이 아닌 `logo.style.ts`에서 이루어지도록 변경되었습니다. 또한, 디자인 시스템에 명시되어 있는 컬러 토큰을 적용해 변경해 주었습니다.
```tsx
import * as S from "./Logo.style";
export default function Logo({ $isFooter = false }: S.ILogo) {
return (
<S.LogoContainer>
<S.LogoIconImg $isFooter={$isFooter} />
<S.LogoTextImg $isFooter={$isFooter} />
</S.LogoContainer>
);
}
```
```ts …
```
> [✨feat]: chip component 구현

- src/components/Chip/Chip.group.tsx
- src/components/Chip/Chip.tsx
- src/components/Chip/Chip.types.ts
- src/stories/Chip/Chip.stories.tsx
> [♻️refactor]: chip component $iconVisible prop 제거

- src/components/Button/Button.style.tsx
- src/components/Button/Button.theme.ts
- src/components/Button/Button.tsx
- src/components/Button/Button.types.ts
- src/stories/Button.stories.tsx
> #33 PR에 지예 님께서 남겨 주신 코멘트를 바탕으로 `button component`를 리팩토링했습니다. 
- `button component`의 `isLeftIconVisible`과 `isRightIconVisible` prop이 삭제되었습니다. 앞으로는 `$leftIcon` 및 `$rightIcon`으로 아이콘 유무를 판단합니다. 
```tsx
export default function Button({
text,
$leftIcon,
$rightIcon,
$size,
$buttonStyle,
$buttonType = "button",
}: IButton) {
```
- `button component`를 사용하는 곳에서 유동적으로 `width` 속성을 변경할 수 있도록 `$width` prop을 추가해 주었습니다. 
```tsx
export default function Button({
text,
$leftIcon,
$rightIcon,
$size,
$buttonStyle,
$buttonType = "button",
$width,
}: IButton) 
```
- `outlined button component`의 `background` 스타일을 추가해 주었습니다. 
```ts
outlinedPrimary: (theme: DefaultTheme) => css`
background: transparent;
border: ${DESIGN_SYSTEM.stroke.normal} solid
${theme.light["border-trans-normal"]};
color: …
```
> [♻️refactor]: button component 불필요한 props 제거 및 스타일 속성 추가

- src/components/InputField/InputField.style.tsx
- src/components/InputField/InputField.tsx
- src/components/InputField/InputField.types.ts
- src/stories/InputField.stories.tsx
#42 
> `label`처럼 스타일 자유도를 부여해야 하는 항목은 아닌 것 같아 prop으로 텍스트만 받아 사용할 수 있도록 추가해 주었습니다. 
```tsx
export default function InputField({
countLimit,
...
}: IInputField) {
...
<S.CountText>{inputValue.length}/{countLimit}</S.CountText>
...
}
```
> `labelText`에서 `label`로 prop 이름을 변경해 준 뒤, 타입 수정을 진행했습니다. `string → React.ReactNode` 앞으로 레이블 사용 시 아래 예시와 같이 사용 가능합니다.
```tsx
export const Default: Story = {
args: {
label: (
<span>
필드 레이블<span style={{ color: "orange" }}>*</span>
</span>
),
...
};
```
> 스타일을 상위 컴포넌트에서 완전히 자유롭게 조정하도록 하는 것보다 전반적인 스타일은 컴포넌트 자체에서 관리하되, 예외 스타일만 상위 컴포넌트에서 관리하는 게 **일관성** 유지에 도움이 된다고 생각했습니다. 따라서 현재 예외로 처리되어야 하는 `$width` prop만 추가해 주었습니다. 
```tsx
import React, { useState } from "react";
import CloseCircle from "@/assets/icons/close-circle-fill.svg";
import InteractionContainer from …
```
> [♻️refactor]: input field component 수정

- .eslintrc.js
- package-lock.json
- package.json
- src/api/interceptor.ts
- src/constants/api.ts
> base URL 및 헤더/쿠키 설정이 완료되었습니다. 앞으로 API 요청 시 `axiosInstance.httpMethod` 형식으로 요청해 주시면 됩니다.
```ts
import axios from "axios";
const baseURL = `${process.env.VITE_API_URL}/api`;
const axiosInstance = axios.create({
baseURL,
headers: {
"Content-Type": "application/json",
},
withCredentials: true,
});
export default axiosInstance;
```
> 현재 요청 가능한 모든 end point의 상수 처리가 완료되었습니다. API 요청 시 아래와 같은 형식으로 요청할 수 있습니다.
```ts
export const getNotices = async () => {
const response = await axiosInstance.get(
END_POINT.notice,
);
return response;
};
```
1. componote-fe should be listed in the project's dependencies
2. Parsing error: ESLint was configured to run on /src/constants/api.ts using parserOptions.project: <tsconfigRootDir>/tsconfig.json
> tsconfig 파일을 못 읽고 있어 경로를 읽을 수 있는 속성과 예외를 추가해 주었습니다. 
``` …
```
> [✨feat]: axios instance 설정 및 api end point 상수 처리

- .eslintrc.js
- src/components/EmptyState/EmptyState.style.ts
- src/components/EmptyState/EmptyState.tsx
- src/components/EmptyState/EmptyState.type.ts
- src/components/index.ts
- src/stories/EmptyState.stories.tsx
> figma [emptyState component 디자인 시스템](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%92%A0%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=7206-1283613&p=f&t=ffsiBrzOt8WbP79N-0)을 기반으로 empty state component 구현을 진행했습니다. 스토리북에서 확인 가능합니다. :>
> eslint에서 `"import/no-extraneous-dependencies": "off",` 규칙을 추가해도 동일한 규칙 위반 에러 메시지가 계속해서 발생해 `parser` 속성을 `babelParser`로 변경해 주었습니다. 
```cjs
import babelParser from "@babel/eslint-parser";
module.exports = {
parser: babelParser, // TypeScript 구문을 파싱할 파서 설정
parserOptions: {
project: "./tsconfig.json", // TypeScript 프로젝트 설정 파일 경로
tsconfigRootDir: __dirname,
},
```
> [✨feat]: empty state component 구현

- .eslintrc.js
- src/components/Pagination/Pagination.item.style.ts
- src/components/Pagination/Pagination.item.tsx
- src/components/Pagination/Pagination.style.ts
- src/components/Pagination/Pagination.tsx
- src/components/Pagination/Pagination.types.ts
- src/components/Pagination/PaginationButton.tsx
- src/components/index.ts
- src/stories/Pagination.stories.tsx
- src/utils/paginationUtils.tsx
> figma [pagination component 디자인 시스템](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%92%A0%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=7206-804147&p=f&t=ffsiBrzOt8WbP79N-0)을 기반으로 pagination component 구현을 진행했습니다. 스토리북에서 확인 가능합니다. :>
```tsx
"use client";
import { useState } from "react";
import { Pagination } from "@/components";
export default function Page() {
const [currentPage, setCurrentPage] = useState(1);
const totalPages = 20;
const handlePageChange = (page: number) => {
setCurrentPage(page);
};
return (
<Pagination
totalPages={totalPages}
currentPage={currentPage}
onPageChange={handlePageChange}
/>
);
}
```
> 한 번에 보이는 최대 페이지 표시 수는 7개여야 하지만, 시간 단축을 위해 한 페이지에 열 개가 표시되도록 우선 구현했습니다! **UX 관련이라고 판단되어 우선 순위를 살짝 미루고,** 모든 …
> [✨feat]: pagination component 구현

- src/components/Feed/Feed.mycomment.style.ts
- src/components/Feed/Feed.mycomment.tsx
- src/components/Feed/Feed.notification.style.ts
- src/components/Feed/Feed.notification.tsx
- src/components/Feed/Feed.types.ts
- src/components/index.ts
- src/stories/Feed/Feed.mycomment.stories.tsx
- src/stories/Feed/Feed.notification.stories.tsx
> figma [feed component 디자인 시스템](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%92%A0%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=7206-848610&p=f&t=ffsiBrzOt8WbP79N-0)을 기반으로 feed component 구현을 진행했습니다. 스토리북에서 확인 가능합니다. :>
> [✨feat]: feed component 구현

- src/components/Button/Button.style.tsx
- src/components/Button/Button.tsx
- src/components/Button/Button.types.ts
- src/components/Comment/Comment.reply.style.ts
- src/components/Comment/Comment.reply.tsx
- src/components/Comment/Comment.style.ts
- src/components/Comment/Comment.tsx
- src/components/Comment/Comment.types.ts
- src/components/Comment/CommentInteraction.tsx
- src/components/Comment/UserSection.style.ts
- src/components/Comment/UserSection.tsx
- src/components/ContextMenu/ContextMenu.style.ts
- src/components/index.ts
- src/styles/GlobalStyle.ts
> figma [comment component 디자인 시스템](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%92%A0%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=7206-848610&p=f&t=ffsiBrzOt8WbP79N-0)을 기반으로 comment component 구현을 진행했습니다.
> 페이지 작업까지 모두 마치면 스토리북에 추가할 예정입니다. 작업 속도가 생각보다 더뎌져서 나중에 추가하는 점 양해 부탁드립니다. 😱
> 기본적인 동작만 될 수 있도록 구현해 뒀기 때문에 예상대로 동작되지는 않고 있습니다. 때문에 댓글 작업 시 수정이 필요합니다.
> [✨feat]: comment component 구현

- src/app/designsystem/page.tsx
- src/components/Comment/Comment.types.ts
- src/constants/messages.ts
> `conflict`를 해결하다가 `}`를 빼 먹는 말도 안 되는 실수를 저질렀습니다....... 😱 
> 그 외 수정된 내용들은 모두 타입 에러입니다!
```ts
export const ANNOUNCE_PAGE_TEXT = {
emptyState: (tabLabel: string) => `아직 ${tabLabel}이 없어요`,
};
export const BOOKMARK_PAGE_TEXT = {
emptyState: (tabLabel: string) => `아직 북마크한 ${tabLabel} 없어요`,
```
> [🔨fix]: vercel 빌드 오류 해결

- src/app/component/[componentId]/page.tsx
- src/components/Banner/Banner.document.style.ts
- src/components/Banner/Banner.document.tsx
- src/components/Banner/Banner.types.ts
- src/components/Callout/Callout.style.ts
- src/components/Callout/Callout.theme.ts
- src/components/Callout/Callout.tsx
- src/components/Callout/Callout.types.ts
- src/components/Layout/Layout.style.ts
- src/components/Pages/ComponentDetail/DocumentSection.style.ts
- src/components/Pages/ComponentDetail/DocumentSection.tsx
- src/components/Pages/ComponentDetail/DocumentSection.types.ts
- src/components/Pages/index.ts
- src/constants/messages.ts
>  figma [component detail page UI 플로우](https://www.figma.com/design/DYKX0B40H5ZVViUtva7HPa/%F0%9F%9F%A8-%EC%BB%B4%ED%8F%AC%EB%85%B8%ED%8A%B8-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=6921-2713035&p=f&t=4oBGwnnw9wheIKM3-0)을 기반으로 component detail page UI 구현을 진행했습니다. 아래와 같습니다.
_**1. callout theme `typography` 속성이 적용되지 않음**_
> callout theme 중 `typography` 속성이 적용되지 않는 문제가 발생했습니다. 
_**2. callout component에서 텍스트 강조가 필요함**_
> 컴포넌트 상세 페이지에서 `참고문헌 및 용례`에서 사용되는 callout component에는 디자인 시스템 개수가 `feedback-information` 컬러로 강조되어야 합니다. 
_**1. callout theme `typography` 속성이 적용되지 않음**_
> 템플릿 리터럴을 인식하지 못하는 것 같아 제거해 주었더니 정상적으로 적용되는 것을 확인할 수 있었습니다. 
```ts
export const CALLOUT_SIZE = {
sm: {
containerPadding: `${DESIGN_SYSTEM.gap.lg} ${DESIGN_SYSTEM.gap.xl}`,
titleText: …
```
> [✨feat]: component detail page UI 구현

- src/api/component.ts
- src/components/ContextMenu/Combobox.style.ts
- src/components/ContextMenu/ContextMenuItem.style.ts
- src/components/InputField/InputField.style.tsx
- src/components/InputField/InputField.tsx
- src/components/NavigationBar/NavigationBar.style.ts
- src/components/NavigationBar/NavigationBar.tsx
- src/constants/api.ts
- src/hooks/api/component/useComponentListInfiniteQuery.ts
- src/hooks/api/component/useSearchComponentInfiniteQuery.ts
- src/store/common/useComboBoxStore.ts
- src/store/common/useSearchStore.ts
- src/types/api/component.ts
- src/utils/extractKorean.ts
> navigation bar component 검색 구현이 일부 완료되었습니다. [기능 명세서 1-3-2](https://www.notion.so/1204-97fc832ca93b42c8a0479f353723fd6d)에서 자세한 내용 확인 가능합니다. :> 당장 눈에 보이는 기능이 먼저라고 생각해 예외 사항 몇 가지는 구현해 두지 않았으니 명세서 비고 참고 부탁드립니다.
_**1. interaction component**_
> interaction component 때문에 input field cancel button이 클릭되지 않는 문제가 발생 중입니다. 현재는 임시 주석 처리 해 둔 상태이며, 논의 후 해결이 필요할 것 같습니다. 
> [기능 명세서 1-3-2](https://www.notion.so/1204-97fc832ca93b42c8a0479f353723fd6d) 비고
> [✨feat]: navigation bar component 검색 구현

- src/api/login.ts
- src/api/signup.ts
- src/components/Pages/Home/MainContent.tsx
- src/components/Pages/Signup/SignupButton/SignupButton.tsx
- src/hooks/api/useLoginMutation.ts
- src/hooks/store/useSignupUserStore.ts
- src/types/api/login.ts
- src/types/api/user.ts
- 회원가입 API 가 일부 수정되어 해당 내용을 반영했습니다.
- `socailAccountId` -> `socialAccountToken`
- 추가로 `number` -> `string` 형도 바뀜
> [♻️refactor]: 로그인 관련 API 수정된 것 반영

- src/components/NavigationBar/NavigationBar.style.ts
- src/components/NavigationBar/NavigationBar.tsx
- src/constants/contextMenuLabels.ts
- Avatar 클릭시 contextMenu 뜨도록 구현
- 마이페이지 클릭시 /profile로 이동
- 로그아웃 클릭시, accessToken 초기화로 로그아웃 임시 구현
> [✨feat]: 상단바의 Avatar 클릭시 context Menu 구현

- src/api/designSystem.ts
- src/components/ContextMenu/ContextMenuItem.style.ts
- src/components/NavigationBar/NavigationBar.tsx
- src/constants/api.ts
- src/hooks/api/designSystem/useSearchDesignSystemInfiniteQuery.ts
- src/types/api/designSystem.ts
> design system 검색 구현을 완료했습니다. 자세한 기능 명세는 [기능 명세서 1-3-2](https://www.notion.so/1204-97fc832ca93b42c8a0479f353723fd6d)에서 확인하실 수 있습니다. :>
> [✨feat]: design system 검색 구현 
